import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import { Toaster } from 'sonner';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${geistSans.variable} h-full antialiased`}>
      <body className='min-h-full flex flex-col'>
        {children}
        <Toaster
          position='top-right'
          toastOptions={{
            unstyled: true
          }}
        />
      </body>
    </html>
  );
}
